


Output_names = { 'a1 g into cg','a1 cg into g','a1 cg into mtc','a1 mtc into cpm','a1 cpm into pm',...
                 'b1 g into cg','b1 cg into g','b1 cg into mtc','b1 mtc into cpm','b1 cpm into pm',...
                 'a2 pm into cpm','a2 cpm into pm','a2 cpm into mtc','a2 mtc into cg','a2 cg into g',...                          
                 'b2 pm into cpm','b2 cpm into pm','b2 cpm into mtc','b2 mtc into cg','b2 cg into g',...
                 'xx a1 G into CBC','xx a1 CBC into G','xx a1 CBC into MTU','xx a1 MTU into GCC','xx a1 GCC into PM',...
                 'xx b1 G into CBC','xx b1 CBC into G','xx b1 CBC into MTU','xx b1 MTU into GCC','xx b1 GCC into PM',...
                 'xx a2 PM into GCC','xx a2 GCC into PM','xx a2 GCC into MTU','xx a2 MTU into CBC','xx a2 CBC into G',...                          
                 'xx b2 PM into GCC','xx b2 GCC into PM','xx b2 GCC into MTU','xx b2 MTU into CBC','xx b2 CBC into G',... %%                     
                 'uu a1 G into CBC','uu a1 CBC into G','uu a1 CBC into MTU','uu a1 MTU into GCC','uu a1 GCC into PM',...
                 'uu b1 G into CBC','uu b1 CBC into G','uu b1 CBC into MTU','uu b1 MTU into GCC','uu b1 GCC into PM',...
                 'uu a2 PM into GCC','uu a2 GCC into PM','uu a2 GCC into MTU','uu a2 MTU into CBC','uu a2 CBC into G',...                          
                 'uu b2 PM into GCC','uu b2 GCC into PM','uu b2 GCC into MTU','uu b2 MTU into CBC','uu b2 CBC into G',...%%                      
                 'yy a1 G into CBC','yy a1 CBC into G','yy a1 CBC into MTU','yy a1 MTU into GCC','yy a1 GCC into PM',...
                 'yy b1 G into CBC','yy b1 CBC into G','yy b1 CBC into MTU','yy b1 MTU into GCC','yy b1 GCC into PM',...
                 'yy a2 PM into GCC','yy a2 GCC into PM','yy a2 GCC into MTU','yy a2 MTU into CBC','yy a2 CBC into G',...                          
                 'yy b2 PM into GCC','yy b2 GCC into PM','yy b2 GCC into MTU','yy b2 MTU into CBC','yy b2 CBC into G',...%%                     
                 'vv a1 G into CBC','vv a1 CBC into G','vv a1 CBC into MTU','vv a1 MTU into GCC',' vv a1 GCC into PM',...
                 'vv b1 G into CBC','vv b1 CBC into G','vv b1 CBC into MTU','vv b1 MTU into GCC',' vv b1 GCC into PM',...
                 'vv a2 PM into GCC','vv a2 GCC into PM','vv a2 GCC into MTU','vv a2 MTU into CBC','vv a2 CBC into G',...                          
                 'vv b2 PM into GCC','vv b2 GCC into PM','vv b2 GCC into MTU','vv b2 MTU into CBC','vv b2 CBC into G',...
                 'cc1 a1 G into CBC','cc1 a1 CBC into G','cc1 a1 CBC into MTU','cc1 a1 MTU into GCC','cc1 a1 GCC into PM',...
                 'cc1 b1 G into CBC','cc1 b1 CBC into G','cc1 b1 CBC into MTU','cc1 b1 MTU into GCC','cc1 b1 GCC into PM',...
                 'cc1 a2 PM into GCC','cc1 a2 GCC into PM','cc1 a2 GCC into MTU','cc1 a2 MTU into CBC','cc1 a2 CBC into G',...                          
                 'cc1 b2 PM into GCC','cc1 b2 GCC into PM','cc1 b2 GCC into MTU','cc1 b2 MTU into CBC','cc1 b2 CBC into G',...
                 'cc2 a1 G into CBC','cc2 a1 CBC into G','cc2 a1 CBC into MTU','cc2 a1 MTU into GCC','cc2 a1 GCC into PM',...
                 'cc2 b1 G into CBC','cc2 b1 CBC into G','cc2 b1 CBC into MTU','cc2 b1 MTU into GCC','cc2 b1 GCC into PM',...
                 'cc2 a2 PM into GCC','cc2 a2 GCC into PM','cc2 a2 GCC into MTU','cc2 a2 MTU into CBC','cc2 a2 CBC into G',...                          
                 'cc2 b2 PM into GCC','cc2 b2 GCC into PM','cc2 b2 GCC into MTU','cc2 b2 MTU into CBC','cc2 b2 CBC into G',...
                 'kk a1 G into CBC','kk a1 CBC into G','kk a1 CBC into MTU','kk a1 MTU into GCC','kk a1 GCC into PM',...
                 'kk b1 G into CBC','kk b1 CBC into G','kk b1 CBC into MTU','kk b1 MTU into GCC','kk b1 GCC into PM',...
                 'kk a2 PM into GCC','kk a2 GCC into PM','kk a2 GCC into MTU','kk a2 MTU into CBC','kk a2 CBC into G',...                          
                 'kk b2 PM into GCC','kk b2 GCC into PM','kk b2 GCC into MTU','kk b2 MTU into CBC','kk b2 CBC into G',...
                 'dd a1 G into CBC','dd a1 CBC into G','dd a1 CBC into MTU','dd a1 MTU into GCC','dd a1 GCC into PM',...
                 'dd b1 G into CBC','dd b1 CBC into G','dd b1 CBC into MTU','dd b1 MTU into GCC','dd b1 GCC into PM',...
                 'dd a2 PM into GCC','dd a2 GCC into PM','dd a2 GCC into MTU','dd a2 MTU into CBC','dd a2 CBC into G',...                          
                 'dd b2 PM into GCC','dd b2 GCC into PM','dd b2 GCC into MTU','dd b2 MTU into CBC','dd b2 CBC into G',...           
                 'velocity a1 MTU to GCC','velocity b1 MTU to GCC','velocity a2 MTU to CBC','velocity b2 MTU to CBC',...          
                 'dyn MTs length','stbl MTs length','MTU length'};

 length_output_rows = length(output_last_timepoints_velocity(:,1));       
       
 length_velocities = length(velocities);
 fontSize = 6;
 LineWidth = 3;
 
 multiplot.Max_rows = 5;
 multiplot.Max_cols = 5;
 multiplot.Max_subplots = multiplot.Max_rows * multiplot.Max_cols;
 multiplot.Index = multiplot.Max_subplots;
 max_xlimit = max(velocities);
 pdf_name = 'C:\\Users\Arjun\Desktop\Experimental_jens\Fluxes.ps';
 
 for indexOutputRow=1:length_output_rows
     multiplot.Index = multiplot.Index + 1;
     if (multiplot.Index > multiplot.Max_subplots)
        multiplot.Index = 1; 
        figure;

        %set(gca,'Position',[10 10 10 10])
     end

     subplot(multiplot.Max_rows, multiplot.Max_cols, multiplot.Index)
     plot(velocities,output_last_timepoints_velocity(indexOutputRow,:) ,'*-','Color',[153/255 0 0.3],'LineWidth',LineWidth);
     xlim([0 max_xlimit]);
     title(char(Output_names(indexOutputRow)), 'FontSize', 6);
    
     if ((multiplot.Index == multiplot.Max_subplots)||(indexOutputRow==length_output_rows))
%          set(gcf,'paperunits','centimeters')
%          set(gcf,'papertype','a4')
%          set(gcf, 'PaperPosition', [-11.73 2.51 34.45 14.69]);
%          set(gcf,'PaperOrientation','landscape');
         print(gcf, '-dpsc', pdf_name,'-append','-fillpage');  
     
  
     end

 end
 for i =1: 8
  print(figure(i),'-dpdf')
 end