
if       (anticipated_velocity                    == 0)
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux025_fraction010_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux025_fraction025_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.5)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux025_fraction050_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux025_fraction075_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.9)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux025_fraction090_velocity005;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux050_fraction010_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux050_fraction025_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux050_fraction050_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux050_fraction075_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux050_fraction090_velocity005;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux075_fraction010_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux075_fraction025_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux075_fraction050_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux075_fraction075_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux075_fraction090_velocity005;
...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux100_fraction010_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux100_fraction025_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux100_fraction050_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux100_fraction075_velocity005;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 5)
           NOG_adoptVariables_backwardFlux100_fraction090_velocity005;
...
...
...
...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux025_fraction010_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux025_fraction025_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.5)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux025_fraction050_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux025_fraction075_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.9)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux025_fraction090_velocity010;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux050_fraction010_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux050_fraction025_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux050_fraction050_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux050_fraction075_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux050_fraction090_velocity010;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux075_fraction010_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux075_fraction025_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux075_fraction050_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux075_fraction075_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux075_fraction090_velocity010;
...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux100_fraction010_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux100_fraction025_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux100_fraction050_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux100_fraction075_velocity010;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 10)
           NOG_adoptVariables_backwardFlux100_fraction090_velocity010;
...
...
...
...

elseif       (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux025_fraction010_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux025_fraction025_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.5)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux025_fraction050_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux025_fraction075_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.9)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux025_fraction090_velocity015;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux050_fraction010_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux050_fraction025_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux050_fraction050_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux050_fraction075_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux050_fraction090_velocity015;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux075_fraction010_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux075_fraction025_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux075_fraction050_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux075_fraction075_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux075_fraction090_velocity015;
...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux100_fraction010_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux100_fraction025_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux100_fraction050_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux100_fraction075_velocity015;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 15)
           NOG_adoptVariables_backwardFlux100_fraction090_velocity015;
...
...
...
...

elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux025_fraction010_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux025_fraction025_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.5)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux025_fraction050_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux025_fraction075_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.25)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.9)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux025_fraction090_velocity020;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux050_fraction010_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux050_fraction025_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux050_fraction050_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux050_fraction075_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.50)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux050_fraction090_velocity020;
    ...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux075_fraction010_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux075_fraction025_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux075_fraction050_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux075_fraction075_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 0.75)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux075_fraction090_velocity020;
...
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.10)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux100_fraction010_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.25)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux100_fraction025_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.50)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux100_fraction050_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.75)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux100_fraction075_velocity020;
elseif   (anticipated_backwardFlux_a2_mtc_into_cg == 1)...
       &&(anticipated_fraction_bound_nb1_mtc      == 0.90)...
       &&(anticipated_velocity                    == 20)
           NOG_adoptVariables_backwardFlux100_fraction090_velocity020;
...
else
    ME = MException('No such combination', ...
        'Combinatino is not considered');
    throw(ME)
end

